# ==============================================================================
# N o d e
# ==============================================================================
node:
  port: 8000

# ==============================================================================
# S U B G R A P H
# ==============================================================================
subgraph:
  account: http://localhost:7002/graphql
  analytics: http://localhost:7303/graphql
  authentication: http://localhost:7501/graphql
  inventory: http://localhost:7302/graphql
  invoice: http://localhost:7202/graphql
  # logstream: http://localhost:7401/graphql
  notification: http://localhost:7402/graphql
  order: http://localhost:7102/graphql
  payment: http://localhost:7201/graphql
  person: http://localhost:7001/graphql
  product: http://localhost:7301/graphql
  profile: http://localhost:7003/graphql
  shoppingCart: http://localhost:7101/graphql
  transaction: http://localhost:7203/graphql

# ==============================================================================
# K A F K A
# ==============================================================================
kafka:
  host: localhost
  groupId: omnixys-gateway-service
